[server]
runOnSave = true

[theme]
base = "dark"
primaryColor = "#bfa94c"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#FFFFFF"

[client]
showSidebarNavigation = false
